# Runtime dependencies for cvutil
# Generated by copy_runtime_deps.cmake

if(NOT DEFINED CVUTIL_RUNTIME_DEPENDENCIES)
  set(CVUTIL_RUNTIME_DEPENDENCIES "")
endif()

set(CVUTIL_RUNTIME_DEPENDENCIES "${CVUTIL_RUNTIME_DEPENDENCIES};${CMAKE_CURRENT_LIST_DIR}/../../../bin/PluginManager.dll")
set(CVUTIL_RUNTIME_DEPENDENCIES "${CVUTIL_RUNTIME_DEPENDENCIES};${CMAKE_CURRENT_LIST_DIR}/../../../bin/RoiManager.dll")
